In [3]:
a = [1,1,0,4,5]
while a.any() > 1:
    print("found")

AttributeError: 'list' object has no attribute 'any'

In [18]:
import torch
offset = torch.tensor([10,50,20,30])
threshold = 20
# a = offset>threshold
# b = a * offset
# print(b)
zero_indices = (offset < threshold).nonzero(as_tuple=True)[0]
print(zero_indices)
if len(zero_indices) == 0:
    print("Pog")
else:
    random_values = torch.randint(1, 100, (len(zero_indices),))
    print(random_values)
    # Replace zeros in tensor 'a' with the random values
    offset[zero_indices] = random_values[:len(zero_indices)]

    print(offset)


tensor([0])
tensor([69])
tensor([69, 50, 20, 30])


In [ ]:
def check_threshold(offsets, drr_values, drr, isocenter_pose, threshold):
    negative_map = (drr_values < threshold).nonzero(as_tuple=True)[0]
    if len(negative_map) > 0:
        random_values = get_random_offset(len(negative_map), device)
        offsets[zero_indices] = random_values[:len(zero_indices)]
    
    return offsets


In [6]:
import torch
def check_threshold(drr_values, threshold):
    print(type((drr_values < threshold)))
    print((drr_values < threshold))

    negative_map = (drr_values < threshold).nonzero(as_tuple=True)[0]
    return negative_map
offset = torch.tensor([10,50,20,30])

check_threshold(offset, 20)

<class 'torch.Tensor'>
tensor([ True, False, False, False])


tensor([0])

4
